[package]
name = "javarandom"
version = "0.1.0"
authors = ["Xydez <thexydez@gmail.com>"]
edition = "2018"
license = "Unlicense"

[dependencies]
serde = { version = "1.0", optional = true, features = ["derive"] }
